### ISSUE TITLE
Call to a member function getId()

### ISSUE THREAD

**Issue by ZahraMousavi** [pkp/oaiJats#14]
Hi. I am trying to install oaiJats on a OJS3.2.1-1. When I am trying to enable the plugin it breaks and I get the following error message in the logfile:
_Fatal error:  Uncaught Error: Call to a member function getId() on null in /srv/ojs/ojs3-devel/webroot/plugins/generic/oaiJats/OAIMetadataFormatPlugin_JATS.inc.php:78
Stack trace:
#0 /srv/ojs/ojs3-devel/webroot/lib/pkp/classes/controllers/grid/plugins/PluginGridHandler.inc.php(246): OAIMetadataFormatPlugin_JATS->setEnabled()
#1 /srv/ojs/ojs3-devel/webroot/lib/pkp/classes/core/PKPRouter.inc.php(391): PluginGridHandler->enable()
#2 /srv/ojs/ojs3-devel/webroot/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest()
#3 /srv/ojs/ojs3-devel/webroot/lib/pkp/classes/core/Dispatcher.inc.php(143): PKPComponentRouter->route()
#4 /srv/ojs/ojs3-devel/webroot/lib/pkp/classes/core/PKPApplication.inc.php(279): Dispatcher->dispatch()
#5 /srv/ojs/ojs3-devel/webroot/index.php(68): PKPApplication->execute()_

I appreciate any help!

**Comment by asmecher** [comment]
@ZahraMousavi, how did you install the plugin? Via the Plugin Gallery, or some other way?

**Comment by ZahraMousavi** [comment]
@asmecher I have tried both uploading via gallery and also cloning the repo with the tag from Github into /plugins/oaiMetadataFormats folder, and I get the same error.

**Comment by asmecher** [comment]
@ZahraMousavi, which are you currently using -- from the Plugin Gallery or via Github? If the latter, what branch are you using?

**Comment by ZahraMousavi** [comment]
@asmecher 
Since I am new in OJS and it is on a test server, I am trying different methods:
When trying Plugin Gallery: oaiJats-v1.0.3-0.tar.gz
When using Git: git checkout tags/v1.0.3-0 -b v1.0.3-0
I have also tried: git checkout stable-3_2_1
And in all of these cases when trying to enable it, I get the same 'Call to a member function getId() on null ...' error in the logfile.

**Comment by asmecher** [comment]
@ZahraMousavi, version 1.0.3- of the OAI Jats plugin is only compatible with OJS 3.1.2-x, not OJS 3.2.1-1. What do you get for the following query in OJS?
```
SELECT * FROM versions WHERE product='ojs2' AND current=1;
```

**Comment by ZahraMousavi** [comment]
@asmecher But it says here, https://github.com/pkp/oaiJats/releases/tag/v1.0.3-0 , that it is compatible with ojs 3.2.1!

Running the query I get:
major | minor | revision | build |   date_installed    | current | product_type | product | product_class_name | lazy_load | sitewide 
-------+-------+----------+-------+---------------------+---------+--------------+---------+--------------------+-----------+----------
     3 |     2 |        1 |     1 | 2020-07-20 11:22:09 |       1 | core         | ojs2    |                    |         0 |        1
(1 row)

**Comment by asmecher** [comment]
You're correct, I misread it -- the "official" list of compatibilities is available in http://pkp.sfu.ca/ojs/xml/plugins.xml.

What do you see for the following query?
```
SELECT * FROM versions WHERE product='oaiJats';
```

**Comment by ZahraMousavi** [comment]
I get the following:
 major | minor | revision | build |   date_installed    | current |        product_type        | product | product_class_name | lazy_load | sitewide 
-------+-------+----------+-------+---------------------+---------+----------------------------+---------+--------------------+-----------+----------
     1 |     0 |        3 |     0 | 2020-07-24 08:20:11 |       1 | plugins.oaiMetadataFormats | oaiJats |                    |         0 |        0

**Comment by ZahraMousavi** [comment]
@asmecher I am looking at the function called 'toXml' in the 'OAIMetadataFormatPlugin_JATS.inc.php' file, which the error seems to be coming from. I can see that for example in line 78, it is initiating $galleys variable which remains unused in the function! and in line 87 it says 'if ($subscriptionRequired && !$subscriptionRequired)' plus initiating an unused variable '$isSubscribedDomain' in the line 86, so I guess, it should have been  'if ($subscriptionRequired && !$isSubscribedDomain)' . 
Well, I don't know anything about the logic of these functions, but they just seemed a bit weird to me!

**Comment by asmecher** [comment]
Hi @ZahraMousavi -- you're right, I've corrected a couple of typos here: https://github.com/pkp/oaiJats/commit/610e4202bf0ece5da297fe0957e12f04ab42b397

As for the error you're encountering (`Call to a member function getId() on null`) -- the `$context` object that seems to be inappropriately set to `null` is supposed to contain a `Journal` object specifying which journal you're enabling the plugin for. I'm confused about why it's not set in this case. What is the URL that you're looking at the plugin list from? (Feel free to obsure the domain name if you like.)

**Comment by ZahraMousavi** [comment]
Hi @asmecher - Ok, thanks for the explanation! I was trying to enable it in the site level! Now I know why it was breaking! I tried and It is working in the Journal level. But, UX-wise, shouldn't it gives a proper error message that it is not possible to enable it in the site level, instead of just breaking? or at least, I think, it should be disabled and unchecked in the site level, with some good explanations.

**Comment by asmecher** [comment]
Ah, this plugin shouldn't be available for enabling on a site-wide basis -- I'll look into why the site administration tools are permitting this. Thanks for helping track it down!
